# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title : Jhorman Tasayco | Software Developer
description: > # this means to ignore newlines until "baseurl:"
    Desarrollador de soluciones web.
baseurl   : "http://jhormantasayco.github.io"
url       : "http://jhormantasayco.github.io" # the base hostname & protocol for your site
full_name : "Jhorman Alexander Tasayco Tasayco"
job       : "Full Stack Web Developer"
location  : "Lima, Perú"
information: >
    Bachiller en Ingeniería de Sistemas. Gestor de soluciones web con más de cinco años de experiencia en la implementación
    de aplicaciones desde la incepción del proyecto hasta su desarrollo, despliegue y soporte continuo..
twitter_page  : https://twitter.com/jhormantasayco
github_page   : https://github.com/jhormantasayco
linkedin_page : https://www.linkedin.com/pub/jhorman-tasayco/55/2b9/487
email         : jhormantasayco@gmail.com
ua_code       : UA-74637512-1
